name: Workflow Demo

on: 
  push

env:
  ACCESS_ID: ${{ secretc.AK }}
  SECRET_KEY: ${{ secrets.SK }}

jobs:
  build:
    runs-on: ubuntu-latest
# hamza khan
    steps:
    - name: Echo ACCESS_ID
      run: echo $ACCESS_ID
    - name: Echo SECRET_KEY
      run: echo $SECRET_KEY
